name: CI

on:
- push
- pull_request

jobs:
  host:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11.0
        - macos-10.15
        - windows-2022
        ruby:
        - head
        - 3.1
        - '3.0'
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - 2.3
        include:
        - { os: ubuntu-20.04, ruby: jruby-9.1 } # Ruby 2.3
        - { os: ubuntu-20.04, ruby: jruby-9.2 } # Ruby 2.5
        - { os: ubuntu-20.04, ruby: truffleruby }
        - { os: windows-2022, ruby: mingw }
        - { os: windows-2019, ruby: mswin }

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: ragel
          brew: ragel
          mingw: ragel

      - run: bundle install

      - run: rake compile

      - run: rake test

      - run: rake build

      - run: gem install pkg/*.gem
