name: Fail

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby: [ jruby-head, jruby ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: ragel
          brew: ragel

      - name: Install dependencies
        run:  bundle install

      - name: Compile
        run:  rake compile

      - name: Test
        run:  rake test
        continue-on-error: true